version: "3"

services:
  client:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

  server:
    build: ./server
    ports:
      - "8080:8080"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"